### ISSUE TITLE
Update JsonSchema.Net dependency

### ISSUE THREAD

**Issue by laurynasr** [gregsdennis/openapi#5]
I tried updating Graeae to use current version of JsonSchema.Net [in my fork](https://github.com/gregsdennis/Graeae/compare/main...laurynasr:Graeae:update-dependencies) but hit a brick wall when trying to make the tests run. Apparently the [previous hack to register draft4](https://github.com/gregsdennis/Graeae/blob/3f8dcb64049aa7b482983447cf720441527faf54/Graeae.Models/SchemaDraft4/Draft4Support.cs#L167) as one of the supported meta-schemas no longer works and I can't figure out a way how to do that in the current version of JsonSchema.Net. 

```console
Setup failed for test fixture Graeae.Models.Tests.TestEnvironment
Json.Schema.JsonSchemaException : Custom meta-schema `$schema` keywords must eventually resolve to a meta-schema for a supported specification version.
StackTrace:    at Json.Schema.SchemaRegistry.DetermineSpecVersion(JsonSchema schema, SchemaRegistry registry)
   at Json.Schema.SchemaRegistry.Scan(Uri baseUri, JsonSchema document)
   at Json.Schema.SchemaRegistry.RegisterSchema(Uri uri, IBaseDocument document)
   at Json.Schema.SchemaRegistry.Register(Uri uri, IBaseDocument document)
   at Json.Schema.SchemaRegistry.Register(IBaseDocument document)
   at Json.Schema.JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
   at Graeae.Models.SchemaDraft4.Draft4Support.InitializeDraft4Schema() in D:\src\Graeae\Graeae.Models\SchemaDraft4\Draft4Support.cs:line 175
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Graeae.Models.SchemaDraft4.Draft4Support.get_Draft4MetaSchema() in D:\src\Graeae\Graeae.Models\SchemaDraft4\Draft4Support.cs:line 31
   at Graeae.Models.SchemaDraft4.Draft4Support.Enable() in D:\src\Graeae\Graeae.Models\SchemaDraft4\Draft4Support.cs:line 190
   at Graeae.Models.Tests.TestEnvironment.Setup() in D:\src\Graeae\Graeae.Models.Tests\TestEnvironment.cs:line 11
```

Also, this kind of change probably deserves a major version bump, but as the current major version is still 0 -- should it become 1.0.0 or 0.3.0?

Any guidance would be very appreciated.

Thanks

**Comment by gregsdennis** [comment]
Thanks for the report.  Nothing has changed in that area of code.  I'll have to investigate.

> Also, this kind of change probably deserves a major version bump, but as the current major version is still 0 -- should it become 1.0.0 or 0.3.0?

Since this is a 0.x (alpha/beta?) version, it's not technically governed by SemVer.  I believe the common practice, and the one that I follow, is that for 0.x versions, the numbers shift down one.  So for 0.2.x, the 2 is treated as "major" and there's just not a patch version.  A breaking change would bump to 0.3.0.

**Comment by gregsdennis** [comment]
Yeah, it looks like the hack was lost with the refactor to move the schema scanning to `SchemaRegistry`.  I'll have to add that back in.

**Comment by gregsdennis** [comment]
@laurynasr that was a strange one to track down.

I ended up also supporting Native AOT with this release, and I found a problem in _JsonPointer.Net_'s package where it seemed to be missing two methods.  Not sure how that hasn't come up elsewhere since _JsonSchema.Net_ is DEFINITELY using those methods.

Anyway, the new version should work for you.
